version: '2'
services:
  ide:
    image: jdekarske/homestri-ur5e:latest
    command: /bin/bash #-c "source /catkin_ws/docker-entrypoint.sh && roslaunch /catkin_ws/src/experimentdevel/launch/gazebo_world.launch"
    stdin_open: true
    tty: true  
    volumes:
      - $PWD/experimentdevel:/catkin_ws/src/experimentdevel
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=958
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: